#!/usr/bin/env python3
"""Garden image pipeline.

Three subcommands:

  convert  Decode an iPhone HEIC, strip ALL metadata, resize for the web, and
           write a conventionally-named JPEG beside a plant record. This is the
           only sanctioned way to add a photo — iPhone HEICs embed GPS, and a
           plain `sips` convert does NOT remove it. Never commit a raw HEIC.

  gallery  Regenerate the thumbnail grid in README.md (between the
           <!-- GALLERY:START --> / <!-- GALLERY:END --> markers) from the
           plant records and the images beside them.

  check    Guardrail for local use and CI: fail if any HEIC is tracked, if any
           committed image carries GPS/location metadata, or if the README
           gallery is out of sync with the records.

Requires Python 3 + Pillow (`pip install pillow`). `convert` also needs macOS
`sips` to decode HEIC (no extra install on a Mac).
"""

from __future__ import annotations

import argparse
import datetime as dt
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
PLANTS_DIR = REPO_ROOT / "plants"
README = REPO_ROOT / "README.md"
LOCATIONS = ("front", "side", "back")

GALLERY_START = "<!-- GALLERY:START -->"
GALLERY_END = "<!-- GALLERY:END -->"
GALLERY_NOTE = (
    "<!-- Generated by scripts/garden.py — do not edit by hand. "
    "Run `python3 scripts/garden.py gallery` after adding photos. -->"
)

IMAGE_EXTS = {".jpg", ".jpeg", ".png", ".gif", ".tif", ".tiff", ".webp"}
HEIC_EXTS = {".heic", ".heif"}

# slug-YYYY-MM.jpg  or  slug-YYYY-MM-2.jpg
PHOTO_RE = re.compile(r"^(?P<slug>.+)-(?P<ym>\d{4}-\d{2})(?:-(?P<n>\d+))?\.jpg$")

MAX_EDGE = 1600
QUALITY = 85
THUMB_WIDTH = 260
COLUMNS = 3


# --------------------------------------------------------------------------- #
# helpers
# --------------------------------------------------------------------------- #
def die(msg: str) -> "NoReturn":  # type: ignore[name-defined]
    print(f"error: {msg}", file=sys.stderr)
    sys.exit(2)


def require_pillow():
    try:
        from PIL import Image  # noqa: F401
    except ModuleNotFoundError:
        die("Pillow is required. Install it with: pip install pillow")


def parse_frontmatter(path: Path) -> dict:
    """Minimal YAML-frontmatter reader for our simple `key: value` records."""
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---"):
        return {}
    end = text.find("\n---", 3)
    if end == -1:
        return {}
    fm: dict[str, str] = {}
    for line in text[3:end].splitlines():
        if ":" not in line or not line.strip() or line.lstrip().startswith("#"):
            continue
        key, _, value = line.partition(":")
        value = value.strip()
        # strip an inline ` # comment` only when the value isn't quoted
        if value and value[0] not in "\"'" and " #" in value:
            value = value.split(" #", 1)[0].strip()
        # strip surrounding quotes only when they actually wrap the value
        if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
            value = value[1:-1]
        fm[key.strip()] = value
    return fm


def gps_present(path: Path) -> bool:
    """True if the image carries a non-empty GPS EXIF block."""
    from PIL import Image

    try:
        img = Image.open(path)
    except Exception:
        return False
    try:
        exif = img.getexif()
    except Exception:
        return False
    if not exif:
        return False
    try:
        gps = exif.get_ifd(0x8825)
    except Exception:
        gps = None
    return bool(gps)


def repo_files() -> list[Path]:
    """Files git would include: tracked + untracked, respecting .gitignore.

    This catches images staged or sitting in the working tree (before commit)
    as well as anything already committed, while ignored originals (*.heic)
    are correctly excluded.
    """
    out = subprocess.run(
        ["git", "ls-files", "--cached", "--others", "--exclude-standard"],
        cwd=REPO_ROOT, capture_output=True, text=True, check=True,
    ).stdout
    return [REPO_ROOT / line for line in out.splitlines() if line]


# --------------------------------------------------------------------------- #
# convert
# --------------------------------------------------------------------------- #
def exif_capture_month(src: Path) -> str | None:
    """Read the capture date from a HEIC via macOS `sips` -> 'YYYY-MM'."""
    if not shutil.which("sips"):
        return None
    res = subprocess.run(
        ["sips", "-g", "creation", str(src)], capture_output=True, text=True
    )
    m = re.search(r"creation:\s*(\d{4}):(\d{2}):", res.stdout)
    return f"{m.group(1)}-{m.group(2)}" if m else None


def clean_jpeg(decoded: Path, dest: Path):
    """Strip ALL metadata, auto-rotate, resize, and write a JPEG."""
    from PIL import Image, ImageOps

    img = ImageOps.exif_transpose(Image.open(decoded))  # bake orientation in
    img.thumbnail((MAX_EDGE, MAX_EDGE))
    # Rebuild as a fresh image so NO metadata (EXIF/GPS) can carry over.
    stripped = Image.new(img.mode, img.size)
    stripped.putdata(list(img.getdata()))
    stripped.save(dest, "JPEG", quality=QUALITY, optimize=True)


def cmd_convert(args):
    require_pillow()
    src = Path(args.src).expanduser().resolve()
    record = Path(args.record).expanduser().resolve()
    if not src.exists():
        die(f"source not found: {src}")
    if not record.exists() or record.suffix != ".md":
        die(f"record not found or not a .md file: {record}")

    slug = record.stem
    ym = args.date or exif_capture_month(src) or dt.date.today().strftime("%Y-%m")
    if not re.fullmatch(r"\d{4}-\d{2}", ym):
        die(f"--date must be YYYY-MM, got {ym!r}")

    dest_dir = record.parent
    dest = dest_dir / f"{slug}-{ym}.jpg"
    n = 2
    while dest.exists():
        dest = dest_dir / f"{slug}-{ym}-{n}.jpg"
        n += 1

    suffix = src.suffix.lower()
    with tempfile.TemporaryDirectory() as tmp:
        if suffix in HEIC_EXTS:
            if not shutil.which("sips"):
                die("sips not found; needed to decode HEIC on this platform")
            decoded = Path(tmp) / "decoded.jpg"
            r = subprocess.run(
                ["sips", "-s", "format", "jpeg", str(src), "--out", str(decoded)],
                capture_output=True, text=True,
            )
            if r.returncode != 0 or not decoded.exists():
                die(f"sips failed to decode {src}: {r.stderr.strip()}")
        else:
            decoded = src
        clean_jpeg(decoded, dest)

    if gps_present(dest):  # belt and suspenders
        dest.unlink(missing_ok=True)
        die("metadata strip FAILED — GPS still present; aborted")

    rel = dest.relative_to(REPO_ROOT)
    print(f"wrote {rel}  (metadata stripped, ≤{MAX_EDGE}px)")
    print(f"  → add to {record.name} frontmatter:  cover: {dest.name}")
    print(f"  → embed in ## Photos:  ![{slug} {ym}]({dest.name})")


# --------------------------------------------------------------------------- #
# gallery
# --------------------------------------------------------------------------- #
def photos_for(record: Path) -> list[Path]:
    slug = record.stem
    out = []
    for p in record.parent.glob(f"{slug}-*.jpg"):
        m = PHOTO_RE.match(p.name)
        if m and m.group("slug") == slug:
            out.append(p)
    # newest last by (year-month, suffix number)
    out.sort(key=lambda p: (
        PHOTO_RE.match(p.name).group("ym"),
        int(PHOTO_RE.match(p.name).group("n") or 0),
    ))
    return out


def cover_for(record: Path, fm: dict) -> Path | None:
    cover = fm.get("cover")
    if cover:
        cand = record.parent / cover
        if cand.exists():
            return cand
        print(f"warning: {record.name} cover '{cover}' not found; using newest",
              file=sys.stderr)
    photos = photos_for(record)
    return photos[-1] if photos else None


def render_cell(record: Path, fm: dict) -> str:
    rel_record = record.relative_to(REPO_ROOT).as_posix()
    name = fm.get("name", record.stem)
    species = fm.get("species", "")
    status = fm.get("status", "")
    cover = cover_for(record, fm)
    if cover:
        rel_img = cover.relative_to(REPO_ROOT).as_posix()
        img = (f'<a href="{rel_record}">'
               f'<img src="{rel_img}" width="{THUMB_WIDTH}" alt="{name}"></a>')
    else:
        img = (f'<a href="{rel_record}">'
               f'<em>no photo yet</em></a>')
    caption = f"<strong><a href=\"{rel_record}\">{name}</a></strong>"
    if species:
        caption += f"<br><em>{species}</em>"
    if status:
        caption += f"<br>{status}"
    return f"{img}<br>{caption}"


def build_gallery() -> str:
    lines = [GALLERY_NOTE]
    for loc in LOCATIONS:
        loc_dir = PLANTS_DIR / loc
        records = sorted(loc_dir.glob("*.md"))
        if not records:
            continue
        lines.append(f"\n### {loc.capitalize()}\n")
        lines.append("<table>")
        for row_start in range(0, len(records), COLUMNS):
            row = records[row_start:row_start + COLUMNS]
            lines.append("  <tr>")
            for rec in row:
                fm = parse_frontmatter(rec)
                cell = render_cell(rec, fm)
                lines.append(f'    <td width="{THUMB_WIDTH + 20}" valign="top">{cell}</td>')
            lines.append("  </tr>")
        lines.append("</table>")
    return "\n".join(lines)


def splice_gallery(text: str, block: str) -> str:
    if GALLERY_START not in text or GALLERY_END not in text:
        die(f"README is missing {GALLERY_START} / {GALLERY_END} markers")
    pre = text[: text.index(GALLERY_START) + len(GALLERY_START)]
    post = text[text.index(GALLERY_END):]
    return f"{pre}\n{block}\n{post}"


def cmd_gallery(args):
    require_pillow()
    text = README.read_text(encoding="utf-8")
    new = splice_gallery(text, build_gallery())
    if new == text:
        print("gallery already up to date")
        return
    README.write_text(new, encoding="utf-8")
    print("README gallery regenerated")


# --------------------------------------------------------------------------- #
# check  (local + CI guardrail)
# --------------------------------------------------------------------------- #
def cmd_check(args):
    require_pillow()
    problems: list[str] = []

    files = repo_files()

    # 1. No raw HEIC may ever be committed.
    heic = [f for f in files if f.suffix.lower() in HEIC_EXTS]
    for f in heic:
        problems.append(f"HEIC committed (never commit originals): {f.relative_to(REPO_ROOT)}")

    # 2. No committed image may carry GPS/location metadata.
    for f in files:
        if f.suffix.lower() in IMAGE_EXTS and f.exists() and gps_present(f):
            problems.append(f"image carries GPS metadata: {f.relative_to(REPO_ROOT)}")

    # 3. README gallery must be in sync with the records.
    text = README.read_text(encoding="utf-8")
    expected = splice_gallery(text, build_gallery())
    if expected != text:
        problems.append("README gallery is stale — run: python3 scripts/garden.py gallery")

    if problems:
        print("check FAILED:", file=sys.stderr)
        for p in problems:
            print(f"  - {p}", file=sys.stderr)
        sys.exit(1)
    print(f"check passed: {len(files)} tracked files, no HEIC, no GPS, gallery in sync")


# --------------------------------------------------------------------------- #
def main():
    parser = argparse.ArgumentParser(description="Garden image pipeline")
    sub = parser.add_subparsers(dest="cmd", required=True)

    c = sub.add_parser("convert", help="HEIC -> stripped, resized JPEG beside a record")
    c.add_argument("src", help="source image (HEIC or other)")
    c.add_argument("record", help="plant record .md the photo belongs to")
    c.add_argument("--date", help="override capture month (YYYY-MM)")
    c.set_defaults(func=cmd_convert)

    g = sub.add_parser("gallery", help="regenerate the README thumbnail grid")
    g.set_defaults(func=cmd_gallery)

    k = sub.add_parser("check", help="guardrail: no HEIC, no GPS, gallery in sync")
    k.set_defaults(func=cmd_check)

    args = parser.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
